[build]
base = "app"
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[plugins]]
package = "@netlify/plugin-csp-nonce"

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "default-src 'self'; style-src 'self'; img-src * data:; script-src 'self'; font-src 'self' data:; connect-src 'self' https://*.execute-api.us-east-1.amazonaws.com/ data: ws://localhost:4003/ws;"

