name = "albawebstudio"
compatibility_date = "2025-07-15"
pages_build_output_dir = ".output/public"

[[d1_databases]]
binding = "DB"
database_name = "albaws-content-db"
database_id = "42eb39b2-fb1f-47e7-8195-9255adb5fdec"
